<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<DebugType Condition="'$(Configuration)'=='Debug'">embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="HarmonyLib">
			<HintPath>$(BepInExAssembliesPath)\0Harmony.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="$(MonkeFramesAssemblyPath)\*.dll">
			<HintPath>%(Identity)</HintPath>
		</Reference>

		<Reference Include="$(GameAssemblyPath)\*.dll"
             Exclude="$(GameAssemblyPath)\mscorlib.dll;$(GameAssemblyPath)\System*.dll;$(GameAssemblyPath)\netstandard.dll">
			<HintPath>%(Identity)</HintPath>
		</Reference>
	</ItemGroup>

</Project>
